=== rositsa-ilieva/XML-Project/mountains.dtd
<!ATTLIST catalogue
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

<!ELEMENT catalogue (mountains, regions)>
<!ELEMENT mountains (mountain+)>
<!ELEMENT mountain (name, description, height, peak, thumbnail)>
<!ATTLIST mountain
    id ID #REQUIRED
    region IDREF #REQUIRED
    type CDATA #REQUIRED
    heightCategory CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT peak (#PCDATA)>
<!ELEMENT thumbnail EMPTY>
<!ATTLIST thumbnail source CDATA #REQUIRED>

<!ELEMENT regions (region+)>
<!ELEMENT region (country, province, city, area)>
<!ATTLIST region
    id ID #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT province (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT area (#PCDATA)>

<!NOTATION jpeg SYSTEM "image/jpeg">
<!ENTITY rila PUBLIC "rila" "https://i.postimg.cc/MGCgBMmX/rila.jpg" NDATA jpeg>
<!ENTITY pirin PUBLIC "pirin" "https://i.postimg.cc/cCZjDpjS/pirin.jpg" NDATA jpeg>
<!ENTITY rodopi PUBLIC "rodopi" "https://i.postimg.cc/4dpqQfWP/rodopi.jpg" NDATA jpeg>
<!ENTITY stara-planina PUBLIC "stara-planina" "https://i.postimg.cc/MHDLgs2j/stara-planina.jpg" NDATA jpeg>
<!ENTITY osogovska PUBLIC "osogovska" "https://i.postimg.cc/c1MPKJg4/osogovska.jpg" NDATA jpeg>
<!ENTITY belasitsa PUBLIC "belasitsa" "https://i.postimg.cc/s2Qt19St/belasitsa.jpg" NDATA jpeg>
<!ENTITY vitosha PUBLIC "vitosha" "https://i.postimg.cc/8CMtqyLP/vitosha.jpg" NDATA jpeg>
<!ENTITY slavyanka PUBLIC "slavyanka" "https://i.postimg.cc/pTBkdp0w/slavyanka.jpg" NDATA jpeg>

<!ENTITY bulgaria "България">
<!ENTITY young "младонагъната">
<!ENTITY old "старонагъната">
<!ENTITY high "висока">
<!ENTITY medium "средно-висока">
<!ENTITY sw "Югозападен">
<!ENTITY sc "Южен централен">
<!ENTITY nc "Северен централен">

=== rositsa-ilieva/XML-Project/mountains.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "mountains.dtd">
<?xml-stylesheet type="text/xsl" href="mountains.xsl"?>
<catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mountains.xsd">
    <mountains>
        <mountain id="mountain0" region="region1" type="&young;" heightCategory="&high;">
            <name>Рила</name>
            <description>Рила е най-високата планина в &bulgaria; и на Балканския полуостров.</description>
            <height>2925</height>
            <peak>Мусала</peak>
            <thumbnail source="rila"/>
        </mountain>
        <mountain id="mountain1" region="region2" type="&young;" heightCategory="&high;">
            <name>Пирин</name>
            <description>Пирин е известна със своите алпийски върхове и красиви езера.</description>
            <height>2914</height>
            <peak>Вихрен</peak>
            <thumbnail source="pirin"/>
        </mountain>
        <mountain id="mountain2" region="region3" type="&old;" heightCategory="&medium;">
            <name>Родопи</name>
            <description>Родопите са дом на богата флора и фауна. Тя е най-обширната планина в &bulgaria;.</description>
            <height>2191</height>
            <peak>Голям Перелик</peak>
            <thumbnail source="rodopi"/>
        </mountain>
        <mountain id="mountain3" region="region4" type="&old;" heightCategory="&high;">
            <name>Стара планина</name>
            <description>Стара планина разделя страната на Северна и Южна &bulgaria;.</description>
            <height>2376</height>
            <peak>Ботев</peak>
            <thumbnail source="stara-planina"/>
        </mountain>
        <mountain id="mountain4" region="region5" type="&old;" heightCategory="&medium;">
            <name>Осоговска планина</name>
            <description>Осоговската планина се намира на границата между &bulgaria; и Северна Македония.</description>
            <height>2251</height>
            <peak>Руен</peak>
            <thumbnail source="osogovska"/>
        </mountain>
        <mountain id="mountain5" region="region6" type="&young;" heightCategory="&high;">
            <name>Беласица</name>
            <description>Беласица е известна с разнообразната си природа и граничното си местоположение.</description>
            <height>2029</height>
            <peak>Радомир</peak>
            <thumbnail source="belasitsa"/>
        </mountain>
        <mountain id="mountain6" region="region7" type="&old;" heightCategory="&medium;">
            <name>Витоша</name>
            <description>Витоша е планината в непосредствена близост до София.</description>
            <height>2290</height>
            <peak>Черни връх</peak>
            <thumbnail source="vitosha"/>
        </mountain>
        <mountain id="mountain7" region="region8" type="&old;" heightCategory="&medium;">
            <name>Славянка</name>
            <description>Славянка е малка, но красива планина в Южна &bulgaria;.</description>
            <height>2212</height>
            <peak>Гоцев връх</peak>
            <thumbnail source="slavyanka"/>
        </mountain>
    </mountains>
</catalogue>
